# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev, master ]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: curl -L 'https://dcm.ist/linux-bin-server' > public/TerminusDB.AppImage && chmod +x public/TerminusDB.AppImage
    - run: npx electron-builder build --linux appimage -p never

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: terminusdb-desktop.AppImage
        path: dist/terminusdb-desktop-0.1.0.AppImage

  build_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: |
        curl -L 'https://dcm.ist/windows-bin-server' > temp.tar.gz
        mkdir public/windows
        cd public/windows
        tar xf ../../temp.tar.gz
        ls
        cd ../../
      shell: bash
    - run: npx electron-builder build -p never

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: "terminusdb-desktop Setup 0.1.0.exe"
        path: "dist/terminusdb-desktop Setup 0.1.0.exe"

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: dev-tag-release

    - uses: actions/download-artifact@v2
      with:
        name: terminusdb-desktop.AppImage

    - uses: actions/download-artifact@v2
      with:
        name: "terminusdb-desktop Setup 0.1.0.exe"

    - name: Create a Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: dev-tag-release
        prerelease: true
        files: |
          "terminusdb-desktop Setup 0.1.0.exe"
          terminusdb-desktop.AppImage
