# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: curl -L 'https://dcm.ist/linux-bin' > public/TerminusDB.AppImage && chmod +x public/TerminusDB.AppImage
    - run: npx electron-builder build --linux appimage -p never

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: terminusdb-desktop.AppImage
        path: dist/terminusdb-desktop-0.1.0.AppImage
        
    - name: Create a Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: dev
        release_name: dev
        prerelease: true
        
    - name: Upload a Release Asset
      uses: actions/upload-release-asset@v1.0.2
      with:
    # The URL for uploading assets to the release
        upload_url: ${{ steps.create_release.outputs.upload_url }}
      # The path to the asset you want to upload
        asset_path: dist/terminusdb-desktop-0.1.0.AppImage
    # The name of the asset you want to upload
        asset_name: TerminusDB-desktop.AppImage
